name: auto.yml

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Add secrets
        run: |
          mkdir -p src/main/resources
          printf "%s" "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml
          printf "%s" "${{ secrets.APPLE_AUTHKEY }}" > src/main/resources/Apple_AuthKey.p8

      - name: Build Spring Boot Application
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test
          ls -la build/libs/

      - name: Deploy to OCI
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USER }}
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |
            sudo systemctl stop status-server || true
            sudo rm -f /opt/status-server/app.jar

      - name: Copy JAR to OCI
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USER }}
          key: ${{ secrets.OCI_SSH_KEY }}
          source: "build/libs/*.jar"
          target: "/tmp/"
          strip_components: 0

      - name: Start Application
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USER }}
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |
            sudo find /tmp/build/libs -name "*-SNAPSHOT.jar" ! -name "*-plain.jar" -exec mv {} /opt/status-server/app.jar \;
            sudo chown ubuntu:ubuntu /opt/status-server/app.jar
            sudo rm -f /opt/status-server/application.yml
            sudo systemctl daemon-reload
            sudo systemctl start status-server
            sleep 3
            sudo systemctl status status-server --no-pager
            sudo journalctl -u status-server -n 50 --no-pager